name: Bug
description: "Found a bug. Note, older versions of Minecraft are unlikely to be fixed."
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: dropdown
    id: modules
    attributes:
      label: Mod Title
      description: Which mod are you talking about?
      multiple: true
      options:
        - XyCraft Core
        - XyCraft World
        - XyCraft Override
        - XyCraft Machines
        - Simple Weather
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: Which version of Minecraft?
      multiple: false
      options:
        - "Neoforge 1.21.0"
        - "Forge 1.20.1"
        - "Forge 1.19.2"
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is it?
      multiple: false
      options:
        - Odd Results
        - Performance
        - Crashing
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    id: modloader
    attributes:
      label: Modloader Version & Mod Versions
      description: What version are you using?
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Describe the issue
      description: What happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Walk us through the issue, one step at a time. We can't help you if we can't follow your footsteps.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots and Videos
      description: If applicable, add screenshots or videos to help explain your suggestion.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any extra context about the issue here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for your time! We'll see what we can do"
