name: Bug
description: "Feature that you'd like to see added or changed in XyCraft. Note, older versions of Minecraft may not be fixed unless the fix is totally required to play."
title: "[Bug]: "
labels: [ "type: bug" ]
body:
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: Which version of Minecraft?
      multiple: false
      options:
        - "1.20.1"
        - "1.19.2"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Severity
      description: How bad is it?
      multiple: false
      options:
        - Odd Results
        - Performance
        - Crashing
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Suggestion
      description: What should be added or changed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Walk us through the issue, one step at a time. We can't help you if we can't follow your footsteps.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots and Videos
      description: If applicable, add screenshots or videos to help explain your suggestion.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any extra context about the suggestion here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for your time! We'll see what we can do"
